name: CI

on:
  workflow_dispatch:
  merge_group:
    types: [ checks_requested ]
  pull_request:
    types: [ opened, ready_for_review, synchronize, review_requested, labeled, reopened ]
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [17, 21]
    permissions:
      # creates a new check with unit test results
      checks: write
      # needs to git diff the repo
      contents: read
      # find the pr for this commit
      issues: read
      # write artifacts and comment on pr related to this
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: corretto

      - name: Build and test application
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_USER: dummy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: Europe/Berlin
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US.UTF-8
        with:
          arguments: build --console=plain

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results (Java ${{ matrix.java-version }})
          path: |
            ./**/build/test-results/test/*.xml
            ./**/build/reports/tests

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
