name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Configure Git user
        run: |
          git config user.email "github@roamingthings.de"
          git config user.name "GitHub Actions"

      - name: Generate release version
        run: echo "REVISION=$(date +"%Y.%m.%d.%H.%M.%S")">> "$GITHUB_ENV"
        env:
          TZ: Europe/Berlin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        env:
          TZ: Europe/Berlin
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US.UTF-8
        run: ./gradlew -Pversion=${{ env.REVISION }} build --info --console=plain

      - name: Publish to GitHub Packages
        env:
          TZ: Europe/Berlin
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US.UTF-8
          GITHUB_PUBLISH_PACKAGES_TOKEN: ${{ github.token }}
        run: ./gradlew -Pversion=${{ env.REVISION }} publish --info --console=plain

      - name: Tag last commit with version
        run: |
          git tag ${{ env.REVISION }}
          git push origin ${{ env.REVISION }}

      - name: Create GitHub Release
        run: |
          gh release create ${{ env.REVISION }} --title "Release ${{ env.REVISION }}" --generate-notes  ./lib/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
