name: Submit dependency graph
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit

      - name: Run a build, generating the dependency graph snapshot which will be submitted
        run: ./gradlew allDependencies
        env:
          GITHUB_USER: dummy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: Europe/Berlin
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US.UTF-8
          CI: true
